import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import { UnstableOrganizationProfile, useOrganization } from "@clerk/nextjs";
import React from "react";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <UnstableOrganizationProfile />
        <div>
          The OrganizationProfile will appear here when you select an organization from the OrganizationSwitcher
        </div>
      </main>
    </div>
  );
}
